import { useState } from "react";
import { useForm } from "react-hook-form";
import { useQueryClient } from "@tanstack/react-query";
import { Link } from "wouter";
import { ArrowRight, Inbox, Send, ShieldCheck } from "lucide-react";
import { getListSupplierItemInquiriesQueryKey, useListSupplierItemInquiries, useUpsertSupplierItemInquiryReply, type SupplierItemInquiry, type SupplierItemInquiryReplyInput } from "@workspace/api-client-react";
import { MainLayout } from "@/components/layout/MainLayout";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { InquiryEmpty, InquiryError, InquiryFacts, InquiryGuard, InquiryHeader, InquiryLoading, statusText } from "@/components/inquiries/shared";
import { useSupplierAuth } from "@/lib/supplier-auth";
import { useBuyerAuth } from "@/lib/buyer-auth";

type Values = { responseStatus: SupplierItemInquiryReplyInput["responseStatus"]; price: string; packageDetails: string; branchAddress: string; note: string };
export default function SupplierInquiriesPage() {
  const { supplier, isLoading: supplierLoading } = useSupplierAuth();
  const { user, isLoading: buyerLoading } = useBuyerAuth();
  const allowed = !!supplier && !user;
  const list = useListSupplierItemInquiries({ query: { queryKey: [...getListSupplierItemInquiriesQueryKey(), supplier?.id], enabled: !supplierLoading && !buyerLoading && allowed, refetchInterval: 45000 } });
  const mutation = useUpsertSupplierItemInquiryReply();
  const queryClient = useQueryClient();
  const [editing, setEditing] = useState<SupplierItemInquiry | null>(null);
  const [error, setError] = useState("");
  const form = useForm<Values>({ defaultValues: { responseStatus: "available", price: "", packageDetails: "", branchAddress: "", note: "" } });
  const open = (inquiry: SupplierItemInquiry) => { setEditing(inquiry); setError(""); form.reset({ responseStatus: inquiry.ownReply?.responseStatus || "available", price: inquiry.ownReply?.price?.toString() || "", packageDetails: inquiry.ownReply?.packageDetails || "", branchAddress: inquiry.ownReply?.branchAddress || "", note: inquiry.ownReply?.note || "" }); };
  const submit = async (values: Values) => {
    if (!editing) return;
    const price = values.price.trim() ? Number(values.price) : undefined;
    if (price !== undefined && (!Number.isFinite(price) || price <= 0)) { form.setError("price", { message: "أدخل سعراً أكبر من صفر" }); return; }
    const data: SupplierItemInquiryReplyInput = { responseStatus: values.responseStatus, ...(price !== undefined ? { price } : {}), ...(values.packageDetails.trim() ? { packageDetails: values.packageDetails.trim() } : {}), ...(values.branchAddress.trim() ? { branchAddress: values.branchAddress.trim() } : {}), ...(values.note.trim() ? { note: values.note.trim() } : {}) };
    setError("");
    try { await mutation.mutateAsync({ id: editing.id, data }); await queryClient.invalidateQueries({ queryKey: getListSupplierItemInquiriesQueryKey() }); setEditing(null); }
    catch { setError("تعذر حفظ الرد. تحقق من التفاصيل وحاول مرة أخرى."); }
  };
  return <MainLayout><InquiryHeader eyebrow="مساحة المورد" title="استفسارات المنتجات الموجهة إليك" description="طلبات محددة من أصحاب الأعمال ضمن أصنافك ومدينتك. أجب عن التوفر والسعر وفرع الاستلام دون مشاركة بيانات التواصل الخاصة بهم." action={<Link href="/supplier/dashboard" data-testid="link-inquiries-supplier-dashboard" className="inquiry-btn inquiry-btn-outline"><ArrowRight className="h-4 w-4" /> لوحة المورد</Link>} /><div className="container mx-auto max-w-6xl flex-1 px-4 py-8 md:py-11">{supplierLoading || buyerLoading ? <InquiryLoading /> : !allowed ? <InquiryGuard kind="supplier" /> : list.isLoading ? <InquiryLoading /> : list.error ? <InquiryError retry={() => void list.refetch()} /> : !list.data?.length ? <InquiryEmpty supplier /> : <><p className="mb-5 flex items-center gap-2 text-sm text-muted-foreground"><Inbox className="h-4 w-4 text-primary" /> تُحدّث القائمة تلقائياً كل 45 ثانية. لا تُرسل إشعارات واتساب تلقائية.</p><div className="space-y-4">{list.data.map(inquiry => <article key={inquiry.id} data-testid={`card-supplier-inquiry-${inquiry.id}`} className="inquiry-surface p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-extrabold text-primary">{inquiry.itemName} · {inquiry.businessName || "نشاط تجاري"}</p><h2 className="mt-1 text-xl font-extrabold">{inquiry.brandOrType}</h2></div><span data-testid={`status-supplier-inquiry-${inquiry.id}`} className="rounded-full bg-secondary px-3 py-1 text-xs font-extrabold">{statusText[inquiry.status]}</span></div><div className="mt-4"><InquiryFacts inquiry={inquiry} /></div>{inquiry.note && <p className="mt-4 rounded-xl bg-secondary/20 p-3 text-sm leading-7">{inquiry.note}</p>}{inquiry.photoUrl && <a href={inquiry.photoUrl} target="_blank" rel="noopener noreferrer" data-testid={`link-supplier-inquiry-photo-${inquiry.id}`} className="mt-3 inline-block text-sm font-bold text-primary underline">عرض الصورة المرجعية</a>}{inquiry.ownReply && <div className="mt-5 rounded-xl border border-primary/15 bg-primary/5 p-4 text-sm leading-7"><div className="flex items-center gap-2 font-extrabold text-primary"><ShieldCheck className="h-4 w-4" /> ردك: {statusText[inquiry.ownReply.responseStatus]}</div>{inquiry.ownReply.price != null && <p>{inquiry.ownReply.price.toLocaleString("ar-SA")} ر.س</p>}{inquiry.ownReply.packageDetails && <p>العبوة: {inquiry.ownReply.packageDetails}</p>}{inquiry.ownReply.branchAddress && <p>الفرع: {inquiry.ownReply.branchAddress}</p>}{inquiry.ownReply.note && <p>{inquiry.ownReply.note}</p>}</div>}{inquiry.status === "active" && <button type="button" data-testid={`button-reply-inquiry-${inquiry.id}`} onClick={() => open(inquiry)} className="inquiry-btn inquiry-btn-primary mt-5"><Send className="h-4 w-4" /> {inquiry.ownReply ? "تعديل الرد" : "إرسال رد خاص"}</button>}</article>)}</div></>}</div>
    {editing && <div role="presentation" className="fixed inset-0 z-[100] flex items-center justify-center overflow-y-auto bg-foreground/50 p-4"><section role="dialog" aria-modal="true" aria-label="الرد على الاستفسار" className="inquiry-surface my-auto w-full max-w-xl p-5 md:p-7"><h2 className="text-xl font-extrabold">الرد على {editing.brandOrType}</h2><p className="mt-1 text-sm text-muted-foreground">ردك خاص بصاحب الاستفسار. لا تظهر لك بيانات اتصاله.</p><Form {...form}><form data-testid="form-supplier-inquiry-reply" onSubmit={form.handleSubmit(submit)} className="mt-6 space-y-4"><FormField control={form.control} name="responseStatus" render={({ field }) => <FormItem><FormLabel>حالة التوفر *</FormLabel><FormControl><select {...field} data-testid="select-reply-status" className="inquiry-field"><option value="available">متوفر</option><option value="unavailable">غير متوفر</option><option value="alternative">بديل متوفر</option></select></FormControl></FormItem>} /><div className="grid gap-4 sm:grid-cols-2"><FormField control={form.control} name="price" render={({ field }) => <FormItem><FormLabel>السعر بالريال (اختياري)</FormLabel><FormControl><input {...field} data-testid="input-reply-price" type="number" min="0.01" step="any" className="inquiry-field" /></FormControl><FormMessage /></FormItem>} /><FormField control={form.control} name="packageDetails" render={({ field }) => <FormItem><FormLabel>تفاصيل العبوة</FormLabel><FormControl><input {...field} data-testid="input-reply-package" maxLength={200} className="inquiry-field" /></FormControl></FormItem>} /></div><FormField control={form.control} name="branchAddress" render={({ field }) => <FormItem><FormLabel>عنوان الفرع</FormLabel><FormControl><input {...field} data-testid="input-reply-branch" maxLength={300} placeholder="الفرع الذي يمكن الاستلام منه" className="inquiry-field" /></FormControl></FormItem>} /><FormField control={form.control} name="note" render={({ field }) => <FormItem><FormLabel>توضيح إضافي</FormLabel><FormControl><textarea {...field} data-testid="textarea-reply-note" maxLength={1000} rows={3} className="inquiry-field resize-y" /></FormControl></FormItem>} />{error && <p role="alert" className="text-sm font-bold text-destructive">{error}</p>}<div className="flex flex-wrap gap-2 border-t border-border pt-4"><button data-testid="button-submit-inquiry-reply" type="submit" disabled={mutation.isPending} className="inquiry-btn inquiry-btn-primary">{mutation.isPending ? "جارٍ الحفظ..." : "حفظ الرد"}</button><button type="button" data-testid="button-cancel-inquiry-reply" disabled={mutation.isPending} onClick={() => setEditing(null)} className="inquiry-btn inquiry-btn-outline">إلغاء</button></div></form></Form></section></div>}
  </MainLayout>;
}