import { AlertCircle, ArrowRight, PackageSearch, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import type { ItemInquiryDetails, ItemInquiryReply } from "@workspace/api-client-react";

export const statusText: Record<string, string> = { active: "مفتوح", closed: "مغلق", expired: "منتهي", available: "متوفر", unavailable: "غير متوفر", alternative: "بديل متوفر" };
export function InquiryHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <header className="border-b border-border bg-secondary/25"><div className="container mx-auto flex flex-col gap-5 px-4 py-9 md:flex-row md:items-end md:justify-between md:py-12"><div><p className="text-sm font-extrabold text-primary">{eyebrow}</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight md:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">{description}</p></div>{action}</div></header>;
}
export function InquiryLoading() { return <div role="status" aria-label="جارٍ تحميل الاستفسارات" className="space-y-4">{[1, 2, 3].map(i => <div key={i} className="inquiry-surface h-44 animate-pulse bg-muted/40" />)}</div>; }
export function InquiryError({ retry }: { retry: () => void }) { return <div role="alert" className="inquiry-surface p-9 text-center"><AlertCircle className="mx-auto h-8 w-8 text-destructive" /><h2 className="mt-3 text-xl font-extrabold">تعذر تحميل الاستفسارات</h2><p className="mt-2 text-sm text-muted-foreground">تحقق من الاتصال ثم حاول مرة أخرى.</p><button data-testid="button-retry-inquiries" type="button" onClick={retry} className="inquiry-btn inquiry-btn-outline mt-5">إعادة المحاولة</button></div>; }
export function InquiryGuard({ kind }: { kind: "buyer" | "owner" | "supplier" }) { return <div className="inquiry-surface mx-auto max-w-lg p-8 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-primary" /><h2 className="mt-4 text-xl font-extrabold">{kind === "owner" ? "الاستفسارات لصاحب العمل فقط" : kind === "supplier" ? "صندوق الاستفسارات للموردين" : "سجّل دخولك لمتابعة استفساراتك"}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">استخدم الحساب المناسب للاطلاع على هذه المساحة. لا تظهر بيانات التواصل في صندوق المورد.</p><Link data-testid="link-inquiry-login" href={kind === "supplier" ? "/supplier/login" : "/buyer/login"} className="inquiry-btn inquiry-btn-primary mt-5">تسجيل الدخول <ArrowRight className="h-4 w-4" /></Link></div>; }
export function InquiryEmpty({ supplier = false }: { supplier?: boolean }) { return <div className="inquiry-surface mx-auto max-w-xl px-7 py-12 text-center"><PackageSearch className="mx-auto h-11 w-11 text-primary/70" /><h2 className="mt-4 text-xl font-extrabold">{supplier ? "لا توجد استفسارات موجهة إليك الآن" : "لم ترسل أي استفسار بعد"}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">{supplier ? "عندما يسأل صاحب عمل عن صنف في مدينتك ومجال توريدك، سيظهر الاستفسار هنا." : "حدد الصنف والعلامة أو النوع المطلوب لنبحث لك عن رد من الموردين المناسبين."}</p>{!supplier && <Link href="/inquiries/new" data-testid="link-empty-new-inquiry" className="inquiry-btn inquiry-btn-primary mt-5">استفسار جديد</Link>}</div>; }
export function InquiryFacts({ inquiry }: { inquiry: ItemInquiryDetails }) { return <div className="flex flex-wrap gap-x-5 gap-y-1 text-sm text-muted-foreground"><span data-testid={`text-inquiry-city-${inquiry.id}`}>{inquiry.city}</span><span>{new Date(inquiry.createdAt).toLocaleDateString("ar-SA", { day: "numeric", month: "long", year: "numeric" })}</span>{inquiry.packageDetails && <span>العبوة: {inquiry.packageDetails}</span>}{inquiry.quantity && <span>الكمية التقريبية: {inquiry.quantity.toLocaleString("ar-SA")}</span>}<span>{inquiry.allowAlternatives ? "يسمح بالبدائل" : "المنتج المحدد فقط"}</span></div>; }
export function ReplyDetails({ reply }: { reply: ItemInquiryReply }) { return <div className="space-y-2 text-sm leading-7"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-extrabold">{reply.supplierBusinessName}</h4><span className="rounded-full bg-secondary px-3 py-1 text-xs font-bold text-primary">{statusText[reply.responseStatus]}</span></div>{reply.price != null && <p className="font-extrabold text-primary" data-testid={`text-reply-price-${reply.supplierId}`}>{reply.price.toLocaleString("ar-SA")} ر.س</p>}{reply.packageDetails && <p>العبوة: {reply.packageDetails}</p>}{reply.branchAddress && <p>عنوان الفرع: {reply.branchAddress}</p>}{reply.note && <p className="text-muted-foreground">{reply.note}</p>}</div>; }