import {
  Apple,
  CakeSlice,
  Candy,
  Cherry,
  Circle,
  Citrus,
  Cookie,
  Croissant,
  Droplets,
  Egg,
  FileText,
  Flame,
  FlaskConical,
  IceCreamCone,
  Leaf,
  Milk,
  Nut,
  Package,
  Palette,
  Pizza,
  Printer,
  Settings,
  ShoppingBag,
  Sparkles,
  SprayCan,
  Wheat,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { ComponentType, SVGProps } from "react";
import { specialIcons } from "../components/category-special-icons";

const categoryIcons: Record<string, LucideIcon> = {
  "🥖": Wheat,
  "🌾": Wheat,
  "🍰": CakeSlice,
  "🧈": Milk,
  "🥛": Milk,
  "🧀": Milk,
  "🍶": Milk,
  "🍦": IceCreamCone,
  "🍫": Candy,
  "🍬": Candy,
  "🍮": CakeSlice,
  "🥜": Nut,
  "🍇": Citrus,
  "🍯": Droplets,
  "🧪": FlaskConical,
  "🌿": Leaf,
  "🎨": Palette,
  "🥟": Croissant,
  "🍕": Pizza,
  "🫓": Wheat,
  "🥐": Croissant,
  "📦": Package,
  "🛍️": ShoppingBag,
  "⚙️": Settings,
  "🔧": Wrench,
  "🍓": Cherry,
  "🥭": Citrus,
  "🛢️": Droplets,
  "🫒": Leaf,
  "🧁": CakeSlice,
  "🍩": CakeSlice,
  "🍑": Citrus,
  "🌰": Nut,
  "🥥": Nut,
  "🌸": Sparkles,
  "🧂": Package,
  "🍪": Cookie,
  "🍒": Cherry,
  "🎂": CakeSlice,
  "📄": FileText,
  "✨": Sparkles,
  "⚪": Circle,
  "🖨️": Printer,
  "💧": Droplets,
  "🧴": SprayCan,
  "🍅": Apple,
  "🥚": Egg,
  "🌶️": Flame,
};

export function getItemCategoryIcon(icon: string): ComponentType<SVGProps<SVGSVGElement>> {
  return specialIcons[icon as keyof typeof specialIcons] ?? categoryIcons[icon] ?? Package;
}